"use client";

import { useState, useEffect } from "react";
import { env, features, validateEnv } from "@/lib/env";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  AlertTriangle,
  CheckCircle,
  XCircle,
  Info,
  FileText,
  Settings,
} from "lucide-react";

type ValidationResult = {
  errors: string[];
  warnings: string[];
} | null;

export default function EnvTestPage() {
  const [validationResult, setValidationResult] =
    useState<ValidationResult>(null);
  const [showRawEnv, setShowRawEnv] = useState(false);

  useEffect(() => {
    // Test environment validation
    try {
      const result = validateEnv();
      setValidationResult(result);
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error occurred";
      setValidationResult({ errors: [errorMessage], warnings: [] });
    }
  }, []);

  const getStatusIcon = (
    value: unknown,
    isRequired: boolean = false,
    isAutoGenerated: boolean = false
  ) => {
    if (isAutoGenerated) {
      return <Settings className="h-4 w-4 text-blue-500" />;
    }
    if (value && value !== "") {
      return <CheckCircle className="h-4 w-4 text-green-500" />;
    } else if (isRequired) {
      return <XCircle className="h-4 w-4 text-red-500" />;
    } else {
      return <AlertTriangle className="h-4 w-4 text-yellow-500" />;
    }
  };

  const getStatusBadge = (
    value: unknown,
    isRequired: boolean = false,
    isAutoGenerated: boolean = false
  ) => {
    if (isAutoGenerated) {
      return (
        <Badge className="bg-blue-100 text-blue-800">Auto-Generated</Badge>
      );
    }
    if (value && value !== "") {
      return <Badge className="bg-green-100 text-green-800">Loaded</Badge>;
    } else if (isRequired) {
      return <Badge className="bg-red-100 text-red-800">Missing</Badge>;
    } else {
      return <Badge className="bg-yellow-100 text-yellow-800">Optional</Badge>;
    }
  };

  const maskValue = (value: string) => {
    if (!value) return "Not set";
    if (value.length <= 8) return "***";
    return `${value.substring(0, 4)}...${value.substring(value.length - 4)}`;
  };

  const isAutoGenerated = (key: string, value: unknown) => {
    return (
      (key === "JWT_SECRET" || key === "SESSION_SECRET") &&
      typeof value === "string" &&
      value.length === 32 &&
      env.NODE_ENV === "development"
    );
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 via-amber-50 to-yellow-100 dark:from-orange-950 dark:via-amber-950 dark:to-yellow-950 p-6">
      <div className="max-w-4xl mx-auto space-y-6">
        <div className="text-center">
          <h1 className="text-3xl font-bold text-orange-800 dark:text-orange-200 mb-2">
            Environment Variables Test
          </h1>
          <p className="text-orange-600 dark:text-orange-400">
            Debug environment variable resolution and validation
          </p>
        </div>

        {/* Status Summary */}
        <Card className="bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm border border-orange-200 dark:border-orange-700">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-orange-800 dark:text-orange-200">
              <Info className="h-5 w-5" />
              Current Status
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="text-center p-4 bg-green-50 dark:bg-green-900/20 rounded-lg">
                <div className="text-2xl font-bold text-green-600 dark:text-green-400">
                  {validationResult?.errors?.length === 0 ? "✅" : "❌"}
                </div>
                <div className="text-sm font-medium text-green-800 dark:text-green-200">
                  Production Ready
                </div>
                <div className="text-xs text-green-600 dark:text-green-400">
                  {validationResult?.errors?.length === 0
                    ? "No critical errors"
                    : `${validationResult?.errors?.length} critical errors`}
                </div>
              </div>
              <div className="text-center p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
                <div className="text-2xl font-bold text-blue-600 dark:text-blue-400">
                  🔧
                </div>
                <div className="text-sm font-medium text-blue-800 dark:text-blue-200">
                  Development Mode
                </div>
                <div className="text-xs text-blue-600 dark:text-blue-400">
                  Auto-generated keys enabled
                </div>
              </div>
              <div className="text-center p-4 bg-yellow-50 dark:bg-yellow-900/20 rounded-lg">
                <div className="text-2xl font-bold text-yellow-600 dark:text-yellow-400">
                  ⚠️
                </div>
                <div className="text-sm font-medium text-yellow-800 dark:text-yellow-200">
                  Optional Warnings
                </div>
                <div className="text-xs text-yellow-600 dark:text-yellow-400">
                  {validationResult?.warnings?.length || 0} optional variables
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Environment Validation Results */}
        <Card className="bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm border border-orange-200 dark:border-orange-700">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-orange-800 dark:text-orange-200">
              <Info className="h-5 w-5" />
              Validation Results
            </CardTitle>
          </CardHeader>
          <CardContent>
            {validationResult && (
              <div className="space-y-4">
                {validationResult.errors.length > 0 && (
                  <div className="p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-700 rounded-lg">
                    <h3 className="font-semibold text-red-800 dark:text-red-200 mb-2">
                      ❌ Critical Errors ({validationResult.errors.length})
                    </h3>
                    <ul className="space-y-1">
                      {validationResult.errors.map(
                        (error: string, index: number) => (
                          <li
                            key={index}
                            className="text-red-700 dark:text-red-300 text-sm"
                          >
                            {error}
                          </li>
                        )
                      )}
                    </ul>
                    <div className="mt-3 p-3 bg-red-100 dark:bg-red-800/30 rounded">
                      <p className="text-sm text-red-800 dark:text-red-200">
                        <strong>Fix:</strong> These errors will prevent the app
                        from running in production. Set the required environment
                        variables in your deployment platform.
                      </p>
                    </div>
                  </div>
                )}
                {validationResult.warnings.length > 0 && (
                  <div className="p-4 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-700 rounded-lg">
                    <h3 className="font-semibold text-yellow-800 dark:text-yellow-200 mb-2">
                      ⚠️ Development Warnings (
                      {validationResult.warnings.length})
                    </h3>
                    <ul className="space-y-1">
                      {validationResult.warnings.map(
                        (warning: string, index: number) => (
                          <li
                            key={index}
                            className="text-yellow-700 dark:text-yellow-300 text-sm"
                          >
                            {warning}
                          </li>
                        )
                      )}
                    </ul>
                    <div className="mt-3 p-3 bg-yellow-100 dark:bg-yellow-800/30 rounded">
                      <p className="text-sm text-yellow-800 dark:text-yellow-200">
                        <strong>Note:</strong> These warnings are for
                        development only. The app will work with fallbacks.
                      </p>
                    </div>
                  </div>
                )}
                {validationResult.errors.length === 0 &&
                  validationResult.warnings.length === 0 && (
                    <div className="p-4 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-700 rounded-lg">
                      <h3 className="font-semibold text-green-800 dark:text-green-200">
                        ✅ All environment variables are properly configured!
                      </h3>
                      <p className="text-sm text-green-700 dark:text-green-300 mt-2">
                        Your application is ready for both development and
                        production.
                      </p>
                    </div>
                  )}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Public Environment Variables */}
        <Card className="bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm border border-orange-200 dark:border-orange-700">
          <CardHeader>
            <CardTitle className="text-orange-800 dark:text-orange-200">
              Public Variables (NEXT_PUBLIC_*)
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              {Object.entries(env)
                .filter(([key]) => key.startsWith("NEXT_PUBLIC_"))
                .map(([key, value]) => (
                  <div
                    key={key}
                    className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-700 rounded-lg"
                  >
                    <div className="flex items-center gap-3">
                      {getStatusIcon(value)}
                      <div>
                        <div className="font-medium text-gray-900 dark:text-gray-100">
                          {key}
                        </div>
                        <div className="text-sm text-gray-600 dark:text-gray-400">
                          {showRawEnv
                            ? String(value)
                            : maskValue(String(value))}
                        </div>
                      </div>
                    </div>
                    {getStatusBadge(value)}
                  </div>
                ))}
            </div>
          </CardContent>
        </Card>

        {/* Server-side Environment Variables */}
        <Card className="bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm border border-orange-200 dark:border-orange-700">
          <CardHeader>
            <CardTitle className="text-orange-800 dark:text-orange-200">
              Server-side Variables
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              {Object.entries(env)
                .filter(([key]) => !key.startsWith("NEXT_PUBLIC_"))
                .map(([key, value]) => {
                  const isRequired = [
                    "DATABASE_URL",
                    "JWT_SECRET",
                    "SESSION_SECRET",
                  ].includes(key);
                  const autoGenerated = isAutoGenerated(key, value);
                  return (
                    <div
                      key={key}
                      className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-700 rounded-lg"
                    >
                      <div className="flex items-center gap-3">
                        {getStatusIcon(value, isRequired, autoGenerated)}
                        <div>
                          <div className="font-medium text-gray-900 dark:text-gray-100">
                            {key}
                          </div>
                          <div className="text-sm text-gray-600 dark:text-gray-400">
                            {showRawEnv
                              ? String(value)
                              : maskValue(String(value))}
                            {autoGenerated && (
                              <span className="ml-2 text-xs text-blue-600 dark:text-blue-400">
                                (auto-generated)
                              </span>
                            )}
                          </div>
                        </div>
                      </div>
                      {getStatusBadge(value, isRequired, autoGenerated)}
                    </div>
                  );
                })}
            </div>
          </CardContent>
        </Card>

        {/* Feature Flags */}
        <Card className="bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm border border-orange-200 dark:border-orange-700">
          <CardHeader>
            <CardTitle className="text-orange-800 dark:text-orange-200">
              Feature Flags
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              {Object.entries(features)
                .filter(([key]) => !key.startsWith("has"))
                .map(([key, value]) => (
                  <div
                    key={key}
                    className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-700 rounded-lg"
                  >
                    <div className="flex items-center gap-3">
                      {value ? (
                        <CheckCircle className="h-4 w-4 text-green-500" />
                      ) : (
                        <XCircle className="h-4 w-4 text-red-500" />
                      )}
                      <div className="font-medium text-gray-900 dark:text-gray-100">
                        {key}
                      </div>
                    </div>
                    <Badge
                      className={
                        value
                          ? "bg-green-100 text-green-800"
                          : "bg-red-100 text-red-800"
                      }
                    >
                      {value ? "Enabled" : "Disabled"}
                    </Badge>
                  </div>
                ))}
            </div>
          </CardContent>
        </Card>

        {/* Service Availability */}
        <Card className="bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm border border-orange-200 dark:border-orange-700">
          <CardHeader>
            <CardTitle className="text-orange-800 dark:text-orange-200">
              Service Availability
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              {Object.entries(features)
                .filter(([key]) => key.startsWith("has"))
                .map(([key, value]) => (
                  <div
                    key={key}
                    className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-700 rounded-lg"
                  >
                    <div className="flex items-center gap-3">
                      {value ? (
                        <CheckCircle className="h-4 w-4 text-green-500" />
                      ) : (
                        <XCircle className="h-4 w-4 text-red-500" />
                      )}
                      <div className="font-medium text-gray-900 dark:text-gray-100">
                        {key
                          .replace("has", "")
                          .replace(/([A-Z])/g, " $1")
                          .trim()}
                      </div>
                    </div>
                    <Badge
                      className={
                        value
                          ? "bg-green-100 text-green-800"
                          : "bg-red-100 text-red-800"
                      }
                    >
                      {value ? "Available" : "Not Available"}
                    </Badge>
                  </div>
                ))}
            </div>
          </CardContent>
        </Card>

        {/* Setup Guide Link */}
        <Card className="bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm border border-orange-200 dark:border-orange-700">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-orange-800 dark:text-orange-200">
              <FileText className="h-5 w-5" />
              Need Help?
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="p-4 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-700 rounded-lg">
              <h3 className="font-semibold text-blue-800 dark:text-blue-200 mb-2">
                📖 Environment Setup Guide
              </h3>
              <p className="text-blue-700 dark:text-blue-300 text-sm mb-3">
                Follow our comprehensive guide to resolve all environment
                variable issues:
              </p>
              <div className="space-y-2 text-sm text-blue-600 dark:text-blue-400">
                <div>
                  • <strong>docs/environment-setup.md</strong> - Complete setup
                  instructions
                </div>
                <div>
                  • Copy <code>.env.example</code> to <code>.env.local</code>
                </div>
                <div>• Update with your actual values</div>
                <div>• Restart your development server</div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Controls */}
        <div className="flex justify-center gap-4">
          <Button
            onClick={() => setShowRawEnv(!showRawEnv)}
            variant="outline"
            className="border-orange-200 dark:border-orange-700 hover:bg-orange-50 dark:hover:bg-orange-900/20 text-orange-700 dark:text-orange-300"
          >
            {showRawEnv ? "Hide" : "Show"} Raw Values
          </Button>
          <Button
            onClick={() => window.location.reload()}
            className="bg-gradient-to-r from-orange-500 via-amber-500 to-yellow-500 hover:from-orange-600 hover:via-amber-600 hover:to-yellow-600 text-white"
          >
            Refresh
          </Button>
        </div>
      </div>
    </div>
  );
}
