"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";

type WorkspaceData = { receipts: Array<{ id: string; order_number: string; snapshot: { subtotal?: number; tax?: number; total?: number }; created_at: string }>; payments: Array<{ id: string; amount: number; currency: string; status: string; created_at: string }>; ledger: Array<{ id: string; amount: number; direction: string; currency: string; status: string; occurred_at: string }>; activity: Array<{ id: string; event_type: string; description: string; occurred_at: string }>; tasks: Array<{ id: string; description: string; metadata: { status?: string }; occurred_at: string }> };

export function EventPayments({ data }: { data: WorkspaceData }) { return <div className="grid gap-3">{data.payments.length ? data.payments.map((payment) => <div key={payment.id} className="flex justify-between rounded-2xl border p-4"><div><p className="font-medium">Receipt transaction</p><p className="text-sm text-muted-foreground">{new Date(payment.created_at).toLocaleString()} · {payment.status}</p></div><p className="font-semibold">{payment.currency} {Number(payment.amount).toFixed(2)}</p></div>) : <Empty text="No receipt transactions matched this event yet." />}</div>; }

export function EventFinance({ data }: { data: WorkspaceData }) { const receipt = data.receipts[0]; const latest = receipt?.snapshot ?? {}; const credits = data.ledger.filter((entry) => entry.direction === "credit"); const ledgerTotal = credits.reduce((sum, item) => sum + Number(item.amount || 0), 0); const receiptTotal = Number(latest.total || 0); const discrepancy = receipt && Math.abs(ledgerTotal - receiptTotal) > 0.01; return <div className="grid gap-4"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Receipt subtotal" value={latest.subtotal} /><Metric label="Receipt VAT / tax" value={latest.tax} /><Metric label="Receipt total" value={latest.total} /></div><div className={`rounded-2xl border p-4 ${discrepancy ? "border-destructive bg-destructive/5" : "border-emerald-300 bg-emerald-50/50"}`}><p className="font-semibold">{discrepancy ? "Finance discrepancy requires review" : "Finance synced"}</p><p className="mt-1 text-sm text-muted-foreground">Latest receipt credits are matched automatically. Ledger credits: GHS {ledgerTotal.toFixed(2)} · Receipt total: GHS {receiptTotal.toFixed(2)}.</p></div>{credits.map((entry) => <div key={entry.id} className="flex items-center justify-between rounded-2xl border p-4"><div><p className="font-medium">Credit entry</p><p className="text-sm text-muted-foreground">{new Date(entry.occurred_at).toLocaleString()} · {entry.status}</p></div><p className="font-semibold">{entry.currency} {Number(entry.amount).toFixed(2)}</p></div>)}</div>; }

export function EventOperations({ event, data, eventId }: { event: { name: string; venue: string; guest_count: number; starts_at: string }; data: WorkspaceData; eventId: string }) { const [open, setOpen] = useState(false); const [description, setDescription] = useState(""); const [tasks, setTasks] = useState(data.tasks); const add = async () => { if (!description.trim()) return; const response = await fetch(`/api/events/${eventId}/workspace`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ description, status: "task" }) }); if (response.ok) { setTasks((current) => [...current, { id: crypto.randomUUID(), description, metadata: { status: "open" }, occurred_at: new Date().toISOString() }]); setDescription(""); setOpen(false); } }; return <div className="grid gap-4"><div className="rounded-2xl border bg-muted/30 p-4"><p className="font-semibold">Setup brief</p><p className="text-sm text-muted-foreground">{event.name} · {event.venue} · {event.guest_count} guests · {new Date(event.starts_at).toLocaleString()}</p></div><Button variant="outline" onClick={() => setOpen((value) => !value)}>{open ? "Close task form" : "Add operational task"}</Button>{open && <div className="flex gap-2"><Input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="e.g. Confirm catering setup" /><Button onClick={() => void add()}>Save task</Button></div>}<div className="grid gap-2">{tasks.map((task) => <div key={task.id} className="flex justify-between rounded-xl border p-3"><span>{task.description}</span><Badge variant="secondary">{task.metadata?.status ?? "open"}</Badge></div>)}</div></div>; }

export function EventDocuments({ eventId, receiptId }: { eventId: string; receiptId?: string | null }) { return <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => window.open(`/events/${eventId}/documents/confirmation`, "_blank")}>Booking confirmation</Button><Button variant="outline" onClick={() => window.open(`/events/${eventId}/documents/invoice`, "_blank")}>Invoice</Button><Button variant="outline" disabled={!receiptId} onClick={() => receiptId && window.open(`/api/hotels/receipts/${receiptId}`, "_blank")}>Receipt</Button></div>; }

export function EventActivity({ data, eventId, receiptId }: { data: WorkspaceData; eventId: string; receiptId?: string | null }) { const [printed, setPrinted] = useState(false); const print = async () => { const response = await fetch(`/api/events/${eventId}/workspace`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ description: `Receipt ${receiptId ?? ""} printed`, eventType: "receipt_printed", receiptId }) }); setPrinted(response.ok); if (receiptId) window.open(`/api/hotels/receipts/${receiptId}`, "_blank", "noopener,noreferrer"); }; return <div className="grid gap-3"><Button variant="outline" className="w-fit" disabled={!receiptId || printed} onClick={() => void print()}> {printed ? "Receipt print logged" : "Print latest receipt"}</Button>{data.activity.length ? data.activity.map((item) => <div key={item.id} className="rounded-xl border p-3"><p className="font-medium">{item.description}</p><p className="text-xs text-muted-foreground">{item.event_type} · {new Date(item.occurred_at).toLocaleString()}</p></div>) : <Empty text="No event activity recorded yet." />}</div>; }

function Metric({ label, value }: { label: string; value?: number }) { return <div className="rounded-2xl border p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">GHS {Number(value || 0).toFixed(2)}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed p-5 text-sm text-muted-foreground">{text}</div>; }
